version: "3"

services:

  server:
    build: app/
    command: main.py
    container_name: server

    ports:
      - 5000:5000

  pytest:
    build: .
    container_name: pytest
    depends_on:
      - server